# Generated by hand for the initial project scaffold.
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecificationUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=24, unique=True)),
                ("title_en", models.CharField(max_length=160)),
                ("title_cy", models.CharField(blank=True, max_length=160)),
                ("description_en", models.TextField(blank=True)),
                ("description_cy", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="GuideArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title_en", models.CharField(max_length=180)),
                ("title_cy", models.CharField(blank=True, max_length=180)),
                ("slug", models.SlugField(max_length=180)),
                ("summary_en", models.TextField(blank=True)),
                ("summary_cy", models.TextField(blank=True)),
                ("body_en", models.TextField()),
                ("body_cy", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("unit", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="guide_articles", to="exams.specificationunit")),
            ],
            options={"ordering": ["order", "title_en"], "unique_together": {("unit", "slug")}},
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("exam_board", models.CharField(choices=[("wjec", "WJEC")], default="wjec", max_length=24)),
                ("series", models.CharField(max_length=24)),
                ("code", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=180)),
                ("source_pdf_path", models.CharField(blank=True, max_length=500)),
                ("mark_scheme_pdf_path", models.CharField(blank=True, max_length=500)),
                ("unit", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="papers", to="exams.specificationunit")),
            ],
            options={"ordering": ["-series", "code"], "unique_together": {("series", "code")}},
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_en", models.CharField(max_length=120)),
                ("name_cy", models.CharField(blank=True, max_length=120)),
                ("slug", models.SlugField(max_length=140)),
                ("unit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="topics", to="exams.specificationunit")),
            ],
            options={"ordering": ["unit__code", "name_en"], "unique_together": {("unit", "slug")}},
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(choices=[("past_paper", "Past paper"), ("generated", "Generated")], default="past_paper", max_length=20)),
                ("reference", models.CharField(blank=True, max_length=80)),
                ("prompt_en", models.TextField()),
                ("prompt_cy", models.TextField(blank=True)),
                ("marks", models.PositiveSmallIntegerField(default=1)),
                ("expected_answer_en", models.TextField()),
                ("expected_answer_cy", models.TextField(blank=True)),
                ("examiner_note_en", models.TextField(blank=True)),
                ("examiner_note_cy", models.TextField(blank=True)),
                ("difficulty", models.CharField(choices=[("foundation", "Foundation"), ("standard", "Standard"), ("stretch", "Stretch")], default="standard", max_length=24)),
                ("is_published", models.BooleanField(default=True)),
                ("paper", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="questions", to="exams.paper")),
                ("topics", models.ManyToManyField(blank=True, related_name="questions", to="exams.topic")),
                ("unit", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="questions", to="exams.specificationunit")),
            ],
            options={"ordering": ["unit__code", "paper__series", "reference", "id"]},
        ),
        migrations.CreateModel(
            name="PracticeAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("answer_text", models.TextField()),
                ("self_assessed_marks", models.PositiveSmallIntegerField(default=0)),
                ("language_code", models.CharField(default="en", max_length=8)),
                ("session_key", models.CharField(blank=True, max_length=80)),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="exams.question")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="WalkthroughStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveSmallIntegerField()),
                ("title_en", models.CharField(max_length=160)),
                ("title_cy", models.CharField(blank=True, max_length=160)),
                ("body_en", models.TextField()),
                ("body_cy", models.TextField(blank=True)),
                ("mark_focus_en", models.CharField(blank=True, max_length=220)),
                ("mark_focus_cy", models.CharField(blank=True, max_length=220)),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="walkthrough_steps", to="exams.question")),
            ],
            options={"ordering": ["question", "order"], "unique_together": {("question", "order")}},
        ),
    ]
