# Generated by Django 4.2.30 on 2026-05-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_userprofile_teacherstudentassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthroughstep',
            name='source_hint_cy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='walkthroughstep',
            name='source_hint_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='walkthroughstep',
            name='write_this_cy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='walkthroughstep',
            name='write_this_en',
            field=models.TextField(blank=True),
        ),
    ]
