# Generated by Django 4.2.30 on 2026-05-03 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_walkthroughstep_source_hint_cy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceattempt',
            name='auto_awarded_marks',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practiceattempt',
            name='auto_feedback_summary',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AttemptFeedbackPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=180)),
                ('awarded', models.BooleanField(default=False)),
                ('marks', models.PositiveSmallIntegerField(default=1)),
                ('evidence', models.TextField(blank=True)),
                ('improvement', models.TextField(blank=True)),
                ('source_hint', models.TextField(blank=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_points', to='exams.practiceattempt')),
            ],
            options={
                'ordering': ['attempt', 'order'],
                'unique_together': {('attempt', 'order')},
            },
        ),
    ]
