# Generated by Django 4.2.30 on 2026-05-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_practiceattempt_auto_awarded_marks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="pattern",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
