PAPERS = [
    {
        "series": "Summer 2019",
        "code": "3500U20-1",
        "title": "WJEC GCSE Computer Science Unit 2",
        "source_pdf_path": "source_materials/wjec-unit2/s19-3500-02.pdf",
        "mark_scheme_pdf_path": "source_materials/wjec-unit2/s19-3500u20-1 wjec gcse comp sci. - unit 2 ms s-ms.pdf",
    },
    {
        "series": "Summer 2022",
        "code": "3500U20-1",
        "title": "WJEC GCSE Computer Science Unit 2",
        "source_pdf_path": "source_materials/wjec-unit2/z22-3500-02.pdf",
        "mark_scheme_pdf_path": "source_materials/wjec-unit2/s22-3500U20-1-ms.pdf",
    },
    {
        "series": "Summer 2023",
        "code": "3500U20-1",
        "title": "WJEC GCSE Computer Science Unit 2",
        "source_pdf_path": "source_materials/wjec-unit2/s23-3500u20-1.pdf",
        "mark_scheme_pdf_path": "source_materials/wjec-unit2/s23-3500u20-1-ms.pdf",
    },
    {
        "series": "Summer 2024",
        "code": "3500U20-1",
        "title": "WJEC GCSE Computer Science Unit 2",
        "source_pdf_path": "source_materials/wjec-unit2/S24-3500U20-1.pdf",
        "mark_scheme_pdf_path": "source_materials/wjec-unit2/S24-3500U20-1-ms.pdf",
    },
]

QUESTION_BANK = [
    {
        "series": "Summer 2019",
        "reference": "2019 Q1",
        "marks": 4,
        "pattern": "html_tags",
        "topics": ["HTML"],
        "prompt": "State the HTML tags needed to: store header metadata; add a list item; define an image; specify quoted text from another source.",
        "answer": "<head>; <li>; <img>; <blockquote>.",
    },
    {
        "series": "Summer 2019",
        "reference": "2019 Q2",
        "marks": 10,
        "pattern": "html_draft",
        "topics": ["HTML"],
        "prompt": "Insert HTML tags to recreate the improved TrackMyPetCare.com page. Use the image file pets.jpg, set the page title to Track My Pet Care, include a heading, image, bullet list, paragraphs and hyperlink, then save as finalPet.txt.",
        "answer": "Use <html>, <head>, <title>Track My Pet Care</title>, <body>, heading/centering tags, <img src=\"pets.jpg\">, paragraphs, <ul>/<li> list items, and <a href=\"http://www.TrackMyPetCare.com\">www.TrackMyPetCare.com</a>.",
    },
    {
        "series": "Summer 2019",
        "reference": "2019 Q3",
        "marks": 4,
        "pattern": "assembly_recall",
        "topics": ["Assembly language"],
        "prompt": "State the assembly language mnemonic to input a value, create a data definition, branch program execution, and subtract a value from a register.",
        "answer": "INP; DAT; BRA; SUB.",
    },
    {
        "series": "Summer 2019",
        "reference": "2019 Q4",
        "marks": 4,
        "pattern": "algorithm_identify",
        "topics": ["Algorithms"],
        "prompt": "From the CountUp algorithm, identify a local variable, a global variable, an annotation, and an assignment.",
        "answer": "Local variable: counter. Global variable: total. Annotation: {Note: the loop has ended here}. Assignment: set counter = 0, set total = 0, counter = counter + 1, or total = total + counter.",
    },
    {
        "series": "Summer 2019",
        "reference": "2019 Q5",
        "marks": 9,
        "pattern": "algorithm_trace",
        "topics": ["Algorithms"],
        "prompt": "Complete the output table for nested loops where i = 1 to 3, j = 1 to 3, outValue = i * j, and outValue is output each time.",
        "answer": "Outputs: 1, 2, 3, 2, 4, 6, 3, 6, 9.",
    },
    {
        "series": "Summer 2019",
        "reference": "2019 Q6",
        "marks": 6,
        "pattern": "algorithm_write",
        "topics": ["Algorithms"],
        "prompt": "Write an algorithm that accepts four pollutant readings, then outputs the total, mean, largest and smallest values.",
        "answer": "Use variables for currentNumber, maxNo, minNo, total and mean; loop four times; input each reading; update max/min using selection; add to total; calculate mean = total / 4; output total, mean, largest and smallest.",
    },
    {
        "series": "Summer 2019",
        "reference": "2019 Q7",
        "marks": 5,
        "pattern": "greenfoot_create",
        "topics": ["Greenfoot", "Greenfoot world setup"],
        "prompt": "Create a Greenfoot aquarium scenario: a world called tank with water.jpg grid background; two fish with fish.jpg; two randomly moving sharks with shark.jpg; one or more crabs with crab.jpg moving left/right only; save as finalAquarium7.",
        "answer": "Marks for tank world/background, two static fish with correct image, two randomly moving sharks with correct image, crab object(s) with correct image moving left/right only, and saving as finalAquarium7.",
    },
    {
        "series": "Summer 2019",
        "reference": "2019 Q8",
        "marks": 5,
        "pattern": "greenfoot_identify",
        "topics": ["Greenfoot"],
        "prompt": "In WJECAnts8 identify a superclass, class, private property, comment, and method automatically run in each frame.",
        "answer": "Superclass: World or Actor. Class: Ground, WaterDrop, Counter, SugarCube or Ant. Private property: counter or totalCount. Comment: Act comment. Automatically run method: act().",
    },
    {
        "series": "Summer 2019",
        "reference": "2019 Q9",
        "marks": 13,
        "pattern": "greenfoot_complete",
        "topics": ["Greenfoot", "Greenfoot collision and scoring"],
        "prompt": "Complete WJECAnts9: populate with one ant, one waterDrop and at least two sugarCube objects; make waterDrop and sugarCube move randomly; move ant with arrow keys; remove sugarCube on collision; play sound; add/increment counter; decrement counter on waterDrop collision; save as finalAnts9.",
        "answer": "Marks for correct population, random movement, arrow-key ant movement at suitable speed, sugarCube removal on collision, sound, counter, increment, decrement via parameter passing, and saving as finalAnts9.",
    },
    {
        "series": "Summer 2022",
        "reference": "2022 Q1",
        "marks": 10,
        "pattern": "html_draft",
        "topics": ["HTML"],
        "prompt": "Insert HTML tags needed to display the improved RobotCleaning page. Use image robot.jpg, page title RobotCleaning, heading RobotCleaning, the robotics paragraph, a bullet list of robot vacuum cleaner, robot mop and robot lawn mower, the hyperlink to www.RobotCleaning.Wjec.co.uk, and save as RobotCleaning.txt.",
        "answer": "Use <html>, <head>, <title>RobotCleaning</title>, <body>, <h1>RobotCleaning</h1>, <img src=\"robot.jpg\">, paragraphs, <ul>/<li> items, and <a href=\"http://www.RobotCleaning.Wjec.co.uk\">www.RobotCleaning.Wjec.co.uk</a>.",
    },
    {
        "series": "Summer 2022",
        "reference": "2022 Q2",
        "marks": 8,
        "pattern": "assembly_recall",
        "topics": ["Assembly language"],
        "prompt": "State the assembly mnemonics to output a value, load a value, store a value and add two values together. Then write an assembly language program to load two values and add them together.",
        "answer": "Recall: OUT, LDA, STA, ADD. Program should use spec mnemonics in a sensible order, with INP, ADD, OUT and HLT credited by the mark scheme.",
    },
    {
        "series": "Summer 2022",
        "reference": "2022 Q3",
        "marks": 4,
        "pattern": "logic_trace",
        "topics": ["Logic"],
        "prompt": "Complete the truth tables for A AND B and for NOT A in the electronic answer document.",
        "answer": "A AND B outputs 0, 0, 0, 1 for 00, 01, 10, 11. NOT A outputs 1 when A is 0 and 0 when A is 1. TRUE/FALSE accepted.",
    },
    {
        "series": "Summer 2022",
        "reference": "2022 Q4",
        "marks": 16,
        "pattern": "algorithm_mixed",
        "topics": ["Algorithms"],
        "prompt": "For the Add subroutine, give all outputs, identify a global variable, local variable, assignment and iteration, then write an algorithm for a 3-hour car survey that inputs readings and outputs total, mean, largest and smallest values.",
        "answer": "Trace outputs: About to add, 0, 1, 2, The total is 3. Identify Total, Counter, initial assignment and do/while loop. Written algorithm should input readings, loop, update total/max/min, calculate mean and output all required values.",
    },
    {
        "series": "Summer 2022",
        "reference": "2022 Q5",
        "marks": 5,
        "pattern": "greenfoot_create",
        "topics": ["Greenfoot", "Greenfoot world setup"],
        "prompt": "Create a Greenfoot garden-centre screen saver: world LeavesWorld with cell.jpg 9 x 9 grid background, class Leaves with leaf.jpg, six Leaves on open, random leaf movement as if blowing in the wind, and save as finalLeaves.",
        "answer": "Marks for LeavesWorld/background, Leaves class with leaf image, six leaves on open, random movement, and saving as finalLeaves or another suitable name accepted by the mark scheme.",
    },
    {
        "series": "Summer 2022",
        "reference": "2022 Q6",
        "marks": 5,
        "pattern": "greenfoot_identify",
        "topics": ["Greenfoot"],
        "prompt": "In WJECTrees6 identify a superclass, a class which inherits from World, a private property, a method, and a parameter.",
        "answer": "World or Actor; Ground; counter or totalCount; act(), bumpCount or a constructor; amount or int amount.",
    },
    {
        "series": "Summer 2022",
        "reference": "2022 Q7",
        "marks": 12,
        "pattern": "greenfoot_complete",
        "topics": ["Greenfoot", "Greenfoot collision and scoring"],
        "prompt": "Complete WJECTrees7: populate the world with a tree, sun and at least two waterDrop instances; make waterDrop and sun move randomly; move tree with arrow keys; remove waterDrop when the tree drinks it; play sound; add/increment counter for waterDrops drunk; decrement counter if sun collides with waterDrop; save as FinalWJECTrees7.",
        "answer": "Marks for population, random movement, arrow-key movement and speed, water removal, sound, counter, increment, decrement, and saving as FinalWJECTrees7.",
    },
    {
        "series": "Summer 2023",
        "reference": "2023 Q1",
        "marks": 5,
        "pattern": "html_tags",
        "topics": ["HTML"],
        "prompt": "State the effect of the HTML tags <i>, <b>, <hr>, <blockquote> and <p>.",
        "answer": "<i> italicises text; <b> emboldens text; <hr> draws a horizontal rule/bar; <blockquote> indicates quoted text; <p> starts/indicates a paragraph.",
    },
    {
        "series": "Summer 2023",
        "reference": "2023 Q2",
        "marks": 10,
        "pattern": "html_draft",
        "topics": ["HTML"],
        "prompt": "Insert HTML tags to recreate the Electric Vehicles page. Use image car.jpg, title Electric Vehicle Information, centered heading, paragraphs, bullet list and hyperlink to www.EV.wjec.co.uk; save as ev.txt.",
        "answer": "Use <html>, <head>, <title>Electric Vehicle Information</title>, <body>, <center>, <h1>, paragraphs, <ul>/<li>, <a href=\"http://www.EV.wjec.co.uk\">www.EV.wjec.co.uk</a>, <img src=\"car.jpg\">.",
    },
    {
        "series": "Summer 2023",
        "reference": "2023 Q3",
        "marks": 10,
        "pattern": "assembly_trace_write",
        "topics": ["Assembly language"],
        "prompt": "Trace an assembly program with inputs 4 and 3, then write an assembly program accepting three numerical inputs and outputting their total only.",
        "answer": "Trace outputs: 4, 3, 4, 1. Program should use INP, STA, LDA, ADD, OUT and HLT to store three inputs, add them and output the total.",
    },
    {
        "series": "Summer 2023",
        "reference": "2023 Q4",
        "marks": 11,
        "pattern": "algorithm_mixed",
        "topics": ["Algorithms"],
        "prompt": "Complete missing lines in a 24-hour car-counting algorithm, explain self-documenting identifiers, and select suitable search algorithms for sorted and unsorted data.",
        "answer": "Missing lines include mean declaration, prompt output, endif, minNo update, smallest output and End Subroutine. Self-documenting identifiers improve readability, understanding, maintenance and consistency. Sorted data: binary search. Unsorted data: linear search.",
    },
    {
        "series": "Summer 2023",
        "reference": "2023 Q5",
        "marks": 6,
        "pattern": "algorithm_write",
        "topics": ["Algorithms"],
        "prompt": "Write an algorithm to input miles for an electric vehicle trip, calculate Time = Number of Miles * 1.5, output time in minutes, and warn if time is over 60 minutes.",
        "answer": "Prompt and input miles, multiply by 1.5 into a time/minutes variable, output the variable, use if minutes > 60 then output the warning.",
    },
    {
        "series": "Summer 2023",
        "reference": "2023 Q6",
        "marks": 5,
        "pattern": "greenfoot_create",
        "topics": ["Greenfoot", "Greenfoot world setup"],
        "prompt": "Create a Greenfoot vehicle showroom scenario: world Advert with cell.jpg grid; class Van with van.jpg; two Vans on open; Vans turn and move randomly; save as finalVans.",
        "answer": "Marks for Advert world/background, Van class with image, two Vans on open, random Van movement, and saved world finalVans/FinalVan accepted ignoring capitalisation.",
    },
    {
        "series": "Summer 2023",
        "reference": "2023 Q7",
        "marks": 13,
        "pattern": "greenfoot_complete",
        "topics": ["Greenfoot", "Greenfoot collision and scoring"],
        "prompt": "Complete WJECCars7: one car, two or more lightning bolts and oil drops; random lightning/oil movement; arrow-key car movement; remove lightning on collision; play sound; counter increments on lightning; decrements on oil; save as FinalWJECCars7.",
        "answer": "Marks for object population, random movement, arrow-key car movement and speed, lightning removal, sound, counter, increment, decrement with parameter passing, and saving as FinalWJECCars7.",
    },
    {
        "series": "Summer 2024",
        "reference": "2024 Q1",
        "marks": 8,
        "pattern": "html_tags",
        "topics": ["HTML"],
        "prompt": "Describe the effect of <blockquote>We choose to go to the moon - JFK</blockquote>, <a href=\"mailto:support@wjec.co.uk\">Send us an email</a>, <h3>Welcome</h3>, and <hr>.",
        "answer": "blockquote creates quoted block text containing the JFK quote; mailto anchor opens an email to support@wjec.co.uk and displays Send us an email as clickable text; h3 creates a heading containing Welcome; hr draws a horizontal rule/bar.",
    },
    {
        "series": "Summer 2024",
        "reference": "2024 Q2",
        "marks": 10,
        "pattern": "html_draft",
        "topics": ["HTML"],
        "prompt": "Insert HTML tags for the Mesh Wi-Fi page. Use image meshw.jpg, page title New! Mesh Wi-Fi, centered heading/image, bullet list, bold Mesh Wi-Fi phrase and hyperlink to www.routers.wjec.co.uk; save as FinalWifi.txt.",
        "answer": "Use <html>, <head>, <title>New! Mesh Wi-Fi</title>, <body>, <center>, <h1>Mesh Wi-Fi</h1>, <img src=\"meshw.jpg\">, <ul>/<li>, <b>Mesh Wi-Fi</b>, and <a href=\"http://www.routers.wjec.co.uk\">Visit www.routers.wjec.co.uk to find out more.</a>.",
    },
    {
        "series": "Summer 2024",
        "reference": "2024 Q3",
        "marks": 13,
        "pattern": "assembly_trace_write",
        "topics": ["Assembly language"],
        "prompt": "State meanings of SUB, BRA, HLT and DAT; state mnemonics for input, output, store and load; trace a program with inputs 1, 2 and 3.",
        "answer": "Meanings: subtract, branch, halt/end/stop, data definition. Mnemonics: INP, OUT, STA, LDA. Trace outputs: 1, 2, 3, 5, 6.",
    },
    {
        "series": "Summer 2024",
        "reference": "2024 Q4",
        "marks": 6,
        "pattern": "algorithm_write",
        "topics": ["Algorithms"],
        "prompt": "Write an algorithm to input how many bus stops there are, input each distance between stops, add them together, and output the total journey distance.",
        "answer": "Output prompt for number of stops, input loop count, loop to input each distance, add each distance to total, then output the total distance variable.",
    },
    {
        "series": "Summer 2024",
        "reference": "2024 Q5",
        "marks": 5,
        "pattern": "greenfoot_create",
        "topics": ["Greenfoot", "Greenfoot world setup"],
        "prompt": "Create a Greenfoot travel advert scenario: world Advert with cell.jpg grid, class Sun with sun.jpg, two Suns on open, random Sun movement, save as finalAdvert.",
        "answer": "Marks for Advert world/background, Sun class with image, two Suns on open, random Sun movement, and saving as finalAdvert.",
    },
    {
        "series": "Summer 2024",
        "reference": "2024 Q6",
        "marks": 5,
        "pattern": "greenfoot_identify",
        "topics": ["Greenfoot"],
        "prompt": "In WJECSki6 identify a private property, a class inheriting from World, a class inheriting from Actor, a method accepting a property, and a superclass.",
        "answer": "private static int totalCount or totalCount; Slopes; Skier, Tree or Snowman; bumpCount method; World or Actor.",
    },
    {
        "series": "Summer 2024",
        "reference": "2024 Q7",
        "marks": 13,
        "pattern": "greenfoot_complete",
        "topics": ["Greenfoot", "Greenfoot collision and scoring"],
        "prompt": "Complete WJECSki7: one Skier, two or more Tree and Snowman objects; random Snowman/Tree movement; arrow-key Skier movement; remove Skier on Snowman collision; play sound; counter gains 1 for Snowman/Tree collision; loses 10 for Skier/Snowman collision; save as FinalWJECSki7.",
        "answer": "Marks for population, random movement, arrow-key skier movement and speed, skier removal, sound, counter, +1 increment, -10 decrement, parameter passing, and saving as FinalWJECSki7.",
    },
]
